#!/usr/bin/env bash

INPUT_FILE=$1
START_LINE=`head -n1 $INPUT_FILE`
PATTERN="^[[:digit:]]+ \[.+ \& .+\] \- .+"
if ! [[ "$START_LINE" =~ $PATTERN ]]; then
  echo "Bad commit message, see example: 268817 [Mike & Ben] - add isolation test for order controller"
  exit 1
fi