#!/bin/sh

if [ "$(uname)" == "Darwin" ]; then
   echo 'MAC'
   ./gradlew clean build
elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
   echo 'Linux'
   ./gradlew clean build
elif [ "$(expr substr $(uname -s) 1 10)" == "MINGW32_NT" ]; then
   echo 'Window 32'
   ./gradlew.bat clean build
elif [ "$(expr substr $(uname -s) 1 10)" == "MINGW64_NT" ]; then
    echo 'Window 64'
   ./gradlew.bat clean build
fi

RESULT=$?

exit $RESULT