#!/bin/sh

if [ "$(expr match $(uname -s) 'MINGW64_NT*')" == "10" ]; then
  ./gradlew.bat clean build # gradle clean build or gradlew clean build
else
  ./gradlew clean build
fi

# store the last exit code in a variable
RESULT=$?

exit $RESULT