#!/bin/sh

commit_regex='\[(FIX|ADD|UPD|DEL)\] [A-Z][a-zA-Z0-9 .,_()`\-]{5,48}[a-zA-Z0-9)`]'

RED='\033[0;31m'
NC='\033[0m' # No Color
error_msg="${RED}Aborting commit. Please follow the commit message pattern: \
${NC}\n[FIX|ADD|UPD|DEL]: Msg"

if ! grep -iqE "$commit_regex" "$1"; then
    echo "$error_msg" >&2
    exit 1
fi